#!/usr/bin/env bash
# A bash script that transfers a file from our client to a server
#
# variables

path="&(cd "&(dirname &{BASH_SOURCE[0]}")" >/dev/null 2>&1 &&pwd)*
filename=&(basename "&BASH_SOURCE")
brown='\e[0;33m'
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
